# Generated by Django 2.2.5 on 2019-11-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=70)),
                ('street', models.CharField(max_length=70)),
                ('building_number', models.IntegerField()),
                ('apartament_number', models.IntegerField(blank=True, default=None, null=True)),
                ('delivery', models.CharField(choices=[('letter', 'letter'), ('package', 'package'), ('courier', 'courier')], max_length=7)),
            ],
        ),
    ]
