# Generated by Django 2.2.5 on 2019-12-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_compliant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compliant',
            new_name='Complaint',
        ),
    ]
