# Generated by Django 2.2.5 on 2019-12-25 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20191222_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Discount'),
        ),
    ]
